eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8400

spring:
  application:
    name: media-service
  data:
    mongodb:
      database: media_service
      uri: mongodb+srv://admin:123@springbootwithmongodb.xffyyfw.mongodb.net/

management:
  tracing:
    sampling:
      probability: 1.0