eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8000

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://user-service.ccdzqrbnif7m.us-east-1.rds.amazonaws.com:1433;databaseName=user_service;encrypt=false;trustServerCertificate=true;sslProtocol=TLSv1.2;
    username: admin
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServer2012Dialect

management:
  tracing:
    sampling:
      probability: 1.0