package com.trvankiet.app.constant;

public enum RoleBasedAuthority {
    ADMIN,
    PRIMARY_SCHOOL_STUDENT, JUNIOR_HIGH_SCHOOL_STUDENT, HIGH_SCHOOL_STUDENT,
    PRIMARY_SCHOOL_TEACHER, JUNIOR_HIGH_SCHOOL_TEACHER, HIGH_SCHOOL_TEACHER,
    PARENT;
}
